version: 2.1

orbs:
  codecov: codecov/codecov@3.2.3

jobs:
  build:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - run:
          name: Build the source
          command: cargo build

  test:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - run:
          name: Run the tests
          command: cargo test

  miri:
    parameters:
      target:
        type: string
    docker:
      - image: jfrimmel/miri:nightly-2022-08-22
    steps:
      - checkout
      - run:
          name: Run the tests
          command: MIRIFLAGS='-Zmiri-symbolic-alignment-check' cargo miri test --target << parameters.target >> --lib

  coverage:
    docker:
      - image: jfrimmel/coverage
    steps:
      - checkout
      - run:
          name: Record testing coverage
          command: |
            env \
              RUSTFLAGS="-C instrument-coverage" \
              LLVM_PROFILE_FILE="json5format-%m.profraw" \
              cargo test
            llvm-profdata merge -sparse json5format-*.profraw -o json5format.profdata
            # according to https://doc.rust-lang.org/rustc/instrument-coverage.html#tips-for-listing-the-binaries-automatically
            llvm-cov report $( \
                for file in $( \
                    RUSTFLAGS="-C instrument-coverage" \
                      cargo test --tests --no-run --message-format=json \
                        | jq -r "select(.profile.test == true) | .filenames[]" \
                        | grep -v dSYM - \
                  ); \
                do printf "%s %s " -object $file; done \
              ) \
              --use-color --ignore-filename-regex='/usr/local/cargo/registry' \
              --instr-profile=json5format.profdata
            # according to https://stackoverflow.com/a/50884416
            llvm-cov export -format=lcov $( \
                for file in $( \
                    RUSTFLAGS="-C instrument-coverage" \
                      cargo test --tests --no-run --message-format=json \
                        | jq -r "select(.profile.test == true) | .filenames[]" \
                        | grep -v dSYM - \
                  ); \
                do printf "%s %s " -object $file; done \
              ) \
              --ignore-filename-regex='/usr/local/cargo/registry' \
              --instr-profile=json5format.profdata > coverage.lcov
      - codecov/upload

  msrv:
    docker:
      - image: rust:1.62
    steps:
      - checkout
      - run:
          name: Build the source
          command: cargo check

  style:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - run:
          name: Install linter and formatter
          command: rustup component add rustfmt clippy
      - run:
          name: Check formatting
          command: cargo fmt --check
      - run:
          name: Run linter
          command: |
            cargo clippy -- \
              -D clippy::cargo \
              -D clippy::complexity \
              -D clippy::nursery \
              -D clippy::pedantic \
              -D clippy::perf \
              -D clippy::style \
              -D clippy::suspicious \
              -F clippy::dbg_macro \
              -F clippy::print_stdout \
              -F clippy::print_stderr \
              -F clippy::todo \
              -F clippy::unimplemented \
              -D clippy::undocumented_unsafe_blocks

  doc:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - run:
          name: Build the documentation
          command: cargo doc

workflows:
  ci:
    jobs:
      - build
      - test:
          requires: [build]
      - miri:
          requires: [build]
          matrix:
            parameters:
              target:
                ["x86_64-unknown-linux-gnu", "mips64-unknown-linux-gnuabi64"]
      - coverage:
          requires: [build]
      - msrv
      - style
      - doc
